name: Checks
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    name: Installation test on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, '[SKIP-CI]')"
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          install:
            - 'install.sh'
    - name: 'Install Google drive upload'
      if: steps.filter.outputs.install == 'true'
      run: |
          set -e
          sh install.sh
              . "${HOME}/.google-drive-upload/google-drive-upload.binpath"
              gupload --info && gsync --help
          sh install.sh -U && sh install.sh --posix -B master
              . "${HOME}/.google-drive-upload/google-drive-upload.binpath"
              gupload --info && gsync --help
          sh install.sh -U  && sh install.sh -c custom_gupload sync="custom_gsync"
              . "${HOME}/.google-drive-upload/google-drive-upload.binpath"
              custom_gupload --info && custom_gsync --help
